project_name: hoard
release:
  github:
    owner: monax
    name: hoard
builds:
- main: ./cmd/hoard
  binary: hoard
  env:
    - CGO_ENABLED=0
  ldflags:
    - -extldflags "-static"
    - -s -w
    - -X github.com/monax/hoard/project.commit={{.Commit}}
    - -X github.com/monax/hoard/project.commit={{.Date}}
- main: ./cmd/hoarctl
  binary: hoarctl
  env:
    - CGO_ENABLED=0
  ldflags:
    - -extldflags "-static"
    - -s -w
    - -X github.com/monax/hoard/project.commit={{.Commit}}
    - -X github.com/monax/hoard/project.commit={{.Date}}
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
