// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: meta.proto

package meta

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Meta struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	MimeType             string   `protobuf:"bytes,2,opt,name=MimeType,proto3" json:"MimeType,omitempty"`
	Tags                 []string `protobuf:"bytes,3,rep,name=Tags,proto3" json:"Tags,omitempty"`
	Agreement            string   `protobuf:"bytes,4,opt,name=Agreement,proto3" json:"Agreement,omitempty"`
	AssemblyEngine       string   `protobuf:"bytes,5,opt,name=AssemblyEngine,proto3" json:"AssemblyEngine,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Meta) Reset()         { *m = Meta{} }
func (m *Meta) String() string { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()    {}
func (*Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{0}
}
func (m *Meta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meta.Unmarshal(m, b)
}
func (m *Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meta.Marshal(b, m, deterministic)
}
func (m *Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meta.Merge(m, src)
}
func (m *Meta) XXX_Size() int {
	return xxx_messageInfo_Meta.Size(m)
}
func (m *Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_Meta proto.InternalMessageInfo

func (m *Meta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Meta) GetMimeType() string {
	if m != nil {
		return m.MimeType
	}
	return ""
}

func (m *Meta) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Meta) GetAgreement() string {
	if m != nil {
		return m.Agreement
	}
	return ""
}

func (m *Meta) GetAssemblyEngine() string {
	if m != nil {
		return m.AssemblyEngine
	}
	return ""
}

type Document struct {
	Meta                 *Meta    `protobuf:"bytes,1,opt,name=Meta,proto3" json:"Meta,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{1}
}
func (m *Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Document.Unmarshal(m, b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Document.Marshal(b, m, deterministic)
}
func (m *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(m, src)
}
func (m *Document) XXX_Size() int {
	return xxx_messageInfo_Document.Size(m)
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func (m *Document) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Document) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Meta)(nil), "meta.Meta")
	proto.RegisterType((*Document)(nil), "meta.Document")
}

func init() { proto.RegisterFile("meta.proto", fileDescriptor_3b5ea8fe65782bcc) }

var fileDescriptor_3b5ea8fe65782bcc = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x31, 0x4b, 0xc5, 0x30,
	0x14, 0x85, 0xa9, 0x2f, 0xca, 0x7b, 0x57, 0x71, 0xc8, 0x14, 0x44, 0x1e, 0xa5, 0x83, 0x38, 0x35,
	0xa0, 0xb8, 0x0a, 0x95, 0x3a, 0xd6, 0xa1, 0x74, 0x72, 0xbb, 0xad, 0x97, 0xb4, 0x60, 0x92, 0xd2,
	0xa6, 0x62, 0xff, 0x85, 0x3f, 0x59, 0x72, 0x85, 0x0a, 0x6f, 0x3b, 0xf9, 0x38, 0x27, 0x7c, 0x5c,
	0x00, 0x4b, 0x01, 0xf3, 0x71, 0xf2, 0xc1, 0x4b, 0x11, 0x73, 0xf6, 0x93, 0x80, 0xa8, 0x28, 0xa0,
	0x94, 0x20, 0xde, 0xd0, 0x92, 0x4a, 0xd2, 0xe4, 0xfe, 0x50, 0x73, 0x96, 0x37, 0xb0, 0xaf, 0x06,
	0x4b, 0xcd, 0x3a, 0x92, 0x3a, 0x63, 0xbe, 0xbd, 0x63, 0xbf, 0x41, 0x33, 0xab, 0x5d, 0xba, 0x8b,
	0xfd, 0x98, 0xe5, 0x2d, 0x1c, 0x0a, 0x33, 0x11, 0x59, 0x72, 0x41, 0x09, 0x1e, 0xfc, 0x03, 0x79,
	0x07, 0xd7, 0xc5, 0x3c, 0x93, 0x6d, 0x3f, 0xd7, 0x57, 0x67, 0x06, 0x47, 0xea, 0x9c, 0x2b, 0x27,
	0x34, 0x7b, 0x86, 0x7d, 0xe9, 0xbb, 0x85, 0x37, 0xc7, 0x3f, 0x3b, 0xb6, 0xba, 0x7c, 0x80, 0x9c,
	0xfd, 0x23, 0xa9, 0x37, 0xeb, 0x12, 0x03, 0xb2, 0xdd, 0x55, 0xcd, 0xf9, 0x25, 0x7d, 0x3f, 0x9a,
	0x21, 0xf4, 0x4b, 0x9b, 0x77, 0xde, 0x6a, 0xeb, 0x1d, 0x7e, 0xeb, 0xde, 0xe3, 0xf4, 0xa1, 0xbf,
	0x9e, 0x74, 0xfc, 0xa0, 0xbd, 0xe0, 0x0b, 0x3c, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0xc1, 0x06,
	0x7d, 0x5f, 0x0f, 0x01, 0x00, 0x00,
}
