// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: stores.proto

package stores

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type StatInfo struct {
	// The address will be the same as the one passed in but is repeated to
	// make result self-describing
	Address []byte `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	// If the blob does not exist this will be false instead of returning an
	// error
	Exists bool `protobuf:"varint,2,opt,name=Exists,proto3" json:"Exists,omitempty"`
	// Will be 0 if the blob does not existing (or omitted under protobuf3)
	Size_ uint64 `protobuf:"varint,3,opt,name=Size,proto3" json:"Size,omitempty"`
	// The externally resolvable location of the encrypted blob. The location
	// will be hypothetical if the blob does not exist
	Location             string   `protobuf:"bytes,4,opt,name=Location,proto3" json:"Location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatInfo) Reset()         { *m = StatInfo{} }
func (m *StatInfo) String() string { return proto.CompactTextString(m) }
func (*StatInfo) ProtoMessage()    {}
func (*StatInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_78bd58a4c4375fca, []int{0}
}
func (m *StatInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatInfo.Unmarshal(m, b)
}
func (m *StatInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatInfo.Marshal(b, m, deterministic)
}
func (m *StatInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatInfo.Merge(m, src)
}
func (m *StatInfo) XXX_Size() int {
	return xxx_messageInfo_StatInfo.Size(m)
}
func (m *StatInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StatInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StatInfo proto.InternalMessageInfo

func (m *StatInfo) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *StatInfo) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

func (m *StatInfo) GetSize_() uint64 {
	if m != nil {
		return m.Size_
	}
	return 0
}

func (m *StatInfo) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func init() {
	proto.RegisterType((*StatInfo)(nil), "stores.StatInfo")
}

func init() { proto.RegisterFile("stores.proto", fileDescriptor_78bd58a4c4375fca) }

var fileDescriptor_78bd58a4c4375fca = []byte{
	// 167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x2e, 0xc9, 0x2f,
	0x4a, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x72, 0xb8, 0x38,
	0x82, 0x4b, 0x12, 0x4b, 0x3c, 0xf3, 0xd2, 0xf2, 0x85, 0x24, 0xb8, 0xd8, 0x1d, 0x53, 0x52, 0x8a,
	0x52, 0x8b, 0x8b, 0x25, 0x18, 0x15, 0x18, 0x35, 0x78, 0x82, 0x60, 0x5c, 0x21, 0x31, 0x2e, 0x36,
	0xd7, 0x8a, 0xcc, 0xe2, 0x92, 0x62, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x8e, 0x20, 0x28, 0x4f, 0x48,
	0x88, 0x8b, 0x25, 0x38, 0xb3, 0x2a, 0x55, 0x82, 0x59, 0x81, 0x51, 0x83, 0x25, 0x08, 0xcc, 0x16,
	0x92, 0xe2, 0xe2, 0xf0, 0xc9, 0x4f, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0x93, 0x60, 0x51, 0x60, 0xd4,
	0xe0, 0x0c, 0x82, 0xf3, 0x9d, 0x94, 0xa2, 0x14, 0xd2, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92,
	0xf3, 0x73, 0xf5, 0x73, 0xf3, 0xf3, 0x12, 0x2b, 0xf4, 0x33, 0xf2, 0x13, 0x8b, 0x52, 0xf4, 0xcb,
	0x4c, 0xf5, 0x21, 0x2e, 0x4a, 0x62, 0x03, 0x3b, 0xd0, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x25,
	0xee, 0x49, 0x43, 0xb0, 0x00, 0x00, 0x00,
}
