// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: reference.proto

package reference

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Ref_RefType int32

const (
	// Default raw reference containing a body chunk
	Ref_BODY Ref_RefType = 0
	// Ref to a header chunk
	Ref_HEADER Ref_RefType = 1
	// A ref to a Plaintext of refs
	Ref_LINK Ref_RefType = 2
)

var Ref_RefType_name = map[int32]string{
	0: "BODY",
	1: "HEADER",
	2: "LINK",
}

var Ref_RefType_value = map[string]int32{
	"BODY":   0,
	"HEADER": 1,
	"LINK":   2,
}

func (x Ref_RefType) String() string {
	return proto.EnumName(Ref_RefType_name, int32(x))
}

func (Ref_RefType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6b165e33ad62994c, []int{0, 0}
}

type Ref struct {
	Address   []byte `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	SecretKey []byte `protobuf:"bytes,2,opt,name=SecretKey,proto3" json:"SecretKey,omitempty"`
	Salt      []byte `protobuf:"bytes,3,opt,name=Salt,proto3" json:"Salt,omitempty"`
	// Version should always have been Type the way it was used (to distinguish a header)
	// unfortunately because version 2 grants rely on JSON serialisation of Ref (for Refs array)
	// We are stuck with this fields while we need to support version 2 grants.
	// Version 3 grants and above use deterministic protobuf serialisation for Refs so have the
	// expected upgrade semantics
	Version int32 `protobuf:"varint,4,opt,name=Version,proto3" json:"Version,omitempty"`
	// Type indicates whether to undergo further decoding
	Type Ref_RefType `protobuf:"varint,5,opt,name=Type,proto3,enum=reference.Ref_RefType" json:"Type,omitempty"`
	// The size in bytes of the plaintext data
	Size_                int64    `protobuf:"varint,6,opt,name=Size,proto3" json:"Size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ref) Reset()         { *m = Ref{} }
func (m *Ref) String() string { return proto.CompactTextString(m) }
func (*Ref) ProtoMessage()    {}
func (*Ref) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b165e33ad62994c, []int{0}
}
func (m *Ref) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ref.Unmarshal(m, b)
}
func (m *Ref) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ref.Marshal(b, m, deterministic)
}
func (m *Ref) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ref.Merge(m, src)
}
func (m *Ref) XXX_Size() int {
	return xxx_messageInfo_Ref.Size(m)
}
func (m *Ref) XXX_DiscardUnknown() {
	xxx_messageInfo_Ref.DiscardUnknown(m)
}

var xxx_messageInfo_Ref proto.InternalMessageInfo

func (m *Ref) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Ref) GetSecretKey() []byte {
	if m != nil {
		return m.SecretKey
	}
	return nil
}

func (m *Ref) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

func (m *Ref) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Ref) GetType() Ref_RefType {
	if m != nil {
		return m.Type
	}
	return Ref_BODY
}

func (m *Ref) GetSize_() int64 {
	if m != nil {
		return m.Size_
	}
	return 0
}

// Note the Salt here is different to the salt that may have been used to encrypt
// the data pointed to by the reference.
type RefsWithNonce struct {
	Refs                 []*Ref   `protobuf:"bytes,1,rep,name=Refs,proto3" json:"Refs,omitempty"`
	Nonce                []byte   `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefsWithNonce) Reset()         { *m = RefsWithNonce{} }
func (m *RefsWithNonce) String() string { return proto.CompactTextString(m) }
func (*RefsWithNonce) ProtoMessage()    {}
func (*RefsWithNonce) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b165e33ad62994c, []int{1}
}
func (m *RefsWithNonce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefsWithNonce.Unmarshal(m, b)
}
func (m *RefsWithNonce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefsWithNonce.Marshal(b, m, deterministic)
}
func (m *RefsWithNonce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefsWithNonce.Merge(m, src)
}
func (m *RefsWithNonce) XXX_Size() int {
	return xxx_messageInfo_RefsWithNonce.Size(m)
}
func (m *RefsWithNonce) XXX_DiscardUnknown() {
	xxx_messageInfo_RefsWithNonce.DiscardUnknown(m)
}

var xxx_messageInfo_RefsWithNonce proto.InternalMessageInfo

func (m *RefsWithNonce) GetRefs() []*Ref {
	if m != nil {
		return m.Refs
	}
	return nil
}

func (m *RefsWithNonce) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func init() {
	proto.RegisterEnum("reference.Ref_RefType", Ref_RefType_name, Ref_RefType_value)
	proto.RegisterType((*Ref)(nil), "reference.Ref")
	proto.RegisterType((*RefsWithNonce)(nil), "reference.RefsWithNonce")
}

func init() { proto.RegisterFile("reference.proto", fileDescriptor_6b165e33ad62994c) }

var fileDescriptor_6b165e33ad62994c = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xdd, 0xe6, 0x4f, 0xed, 0xa8, 0x35, 0x0c, 0x22, 0x7b, 0xf0, 0x10, 0x22, 0x42, 0xf4,
	0x90, 0x40, 0xbd, 0x78, 0x6d, 0x69, 0xc1, 0x52, 0xa9, 0xb0, 0x15, 0x45, 0x6f, 0x69, 0x32, 0x31,
	0x01, 0x9b, 0x2d, 0x9b, 0x28, 0xd6, 0x0f, 0xea, 0xe7, 0x91, 0x5d, 0xfb, 0x87, 0x1e, 0x16, 0xe6,
	0xbd, 0xdf, 0xe3, 0xed, 0xee, 0xc0, 0xa9, 0xa2, 0x9c, 0x14, 0x55, 0x29, 0x45, 0x4b, 0x25, 0x1b,
	0x89, 0x9d, 0xad, 0x11, 0xfc, 0x32, 0xb0, 0x04, 0xe5, 0xc8, 0xa1, 0xdd, 0xcf, 0x32, 0x45, 0x75,
	0xcd, 0x99, 0xcf, 0xc2, 0x63, 0xb1, 0x91, 0x78, 0x01, 0x9d, 0x19, 0xa5, 0x8a, 0x9a, 0x09, 0xad,
	0x78, 0xcb, 0xb0, 0x9d, 0x81, 0x08, 0xf6, 0x2c, 0xf9, 0x68, 0xb8, 0x65, 0x80, 0x99, 0x75, 0xd7,
	0x33, 0xa9, 0xba, 0x94, 0x15, 0xb7, 0x7d, 0x16, 0x3a, 0x62, 0x23, 0xf1, 0x06, 0xec, 0xa7, 0xd5,
	0x92, 0xb8, 0xe3, 0xb3, 0xb0, 0xdb, 0x3b, 0x8f, 0x76, 0x0f, 0x13, 0x94, 0xeb, 0xa3, 0xa9, 0x30,
	0x19, 0xd3, 0x5c, 0xfe, 0x10, 0x77, 0x7d, 0x16, 0x5a, 0xc2, 0xcc, 0xc1, 0x35, 0xb4, 0xd7, 0x21,
	0x3c, 0x04, 0x7b, 0xf0, 0x38, 0x7c, 0xf5, 0x0e, 0x10, 0xc0, 0xbd, 0x1f, 0xf5, 0x87, 0x23, 0xe1,
	0x31, 0xed, 0x3e, 0x8c, 0xa7, 0x13, 0xaf, 0x15, 0x8c, 0xe1, 0x44, 0x50, 0x5e, 0xbf, 0x94, 0x4d,
	0x31, 0x95, 0x55, 0x4a, 0x18, 0x80, 0xad, 0x0d, 0xce, 0x7c, 0x2b, 0x3c, 0xea, 0x75, 0xf7, 0xef,
	0x16, 0x86, 0xe1, 0x19, 0x38, 0x95, 0x0e, 0xaf, 0xff, 0xf9, 0x2f, 0x06, 0x57, 0x6f, 0x97, 0xef,
	0x65, 0x53, 0x7c, 0xce, 0xa3, 0x54, 0x2e, 0xe2, 0x85, 0xac, 0x92, 0xef, 0xb8, 0x90, 0x89, 0xca,
	0xe2, 0xaf, 0xbb, 0x78, 0x5b, 0x33, 0x77, 0xcd, 0x72, 0x6f, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x01, 0x78, 0x62, 0x0c, 0x6f, 0x01, 0x00, 0x00,
}
