// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: grant.proto

package grant

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// As the grant is often stored as json and we to specify the correct tags for
// compatability with the client library.
type Grant struct {
	// The grantSpec provides sufficient information to decrypt the reference
	// if hoard has access to the requisite secret
	Spec                 *Spec    `protobuf:"bytes,1,opt,name=Spec,json=spec,proto3" json:"spec"`
	EncryptedReferences  []byte   `protobuf:"bytes,2,opt,name=EncryptedReferences,json=encryptedreferences,proto3" json:"encryptedreferences"`
	Version              int32    `protobuf:"varint,3,opt,name=Version,json=version,proto3" json:"version"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Grant) Reset()         { *m = Grant{} }
func (m *Grant) String() string { return proto.CompactTextString(m) }
func (*Grant) ProtoMessage()    {}
func (*Grant) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8d80872b3060482, []int{0}
}
func (m *Grant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Grant.Unmarshal(m, b)
}
func (m *Grant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Grant.Marshal(b, m, deterministic)
}
func (m *Grant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Grant.Merge(m, src)
}
func (m *Grant) XXX_Size() int {
	return xxx_messageInfo_Grant.Size(m)
}
func (m *Grant) XXX_DiscardUnknown() {
	xxx_messageInfo_Grant.DiscardUnknown(m)
}

var xxx_messageInfo_Grant proto.InternalMessageInfo

func (m *Grant) GetSpec() *Spec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *Grant) GetEncryptedReferences() []byte {
	if m != nil {
		return m.EncryptedReferences
	}
	return nil
}

func (m *Grant) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type Spec struct {
	Plaintext            *PlaintextSpec `protobuf:"bytes,1,opt,name=Plaintext,json=plaintext,proto3" json:"plaintext"`
	Symmetric            *SymmetricSpec `protobuf:"bytes,2,opt,name=Symmetric,json=symmetric,proto3" json:"symmetric"`
	OpenPGP              *OpenPGPSpec   `protobuf:"bytes,3,opt,name=OpenPGP,json=openpgp,proto3" json:"openpgp"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Spec) Reset()         { *m = Spec{} }
func (m *Spec) String() string { return proto.CompactTextString(m) }
func (*Spec) ProtoMessage()    {}
func (*Spec) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8d80872b3060482, []int{1}
}
func (m *Spec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Spec.Unmarshal(m, b)
}
func (m *Spec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Spec.Marshal(b, m, deterministic)
}
func (m *Spec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Spec.Merge(m, src)
}
func (m *Spec) XXX_Size() int {
	return xxx_messageInfo_Spec.Size(m)
}
func (m *Spec) XXX_DiscardUnknown() {
	xxx_messageInfo_Spec.DiscardUnknown(m)
}

var xxx_messageInfo_Spec proto.InternalMessageInfo

func (m *Spec) GetPlaintext() *PlaintextSpec {
	if m != nil {
		return m.Plaintext
	}
	return nil
}

func (m *Spec) GetSymmetric() *SymmetricSpec {
	if m != nil {
		return m.Symmetric
	}
	return nil
}

func (m *Spec) GetOpenPGP() *OpenPGPSpec {
	if m != nil {
		return m.OpenPGP
	}
	return nil
}

type PlaintextSpec struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaintextSpec) Reset()         { *m = PlaintextSpec{} }
func (m *PlaintextSpec) String() string { return proto.CompactTextString(m) }
func (*PlaintextSpec) ProtoMessage()    {}
func (*PlaintextSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8d80872b3060482, []int{2}
}
func (m *PlaintextSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaintextSpec.Unmarshal(m, b)
}
func (m *PlaintextSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaintextSpec.Marshal(b, m, deterministic)
}
func (m *PlaintextSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaintextSpec.Merge(m, src)
}
func (m *PlaintextSpec) XXX_Size() int {
	return xxx_messageInfo_PlaintextSpec.Size(m)
}
func (m *PlaintextSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaintextSpec.DiscardUnknown(m)
}

var xxx_messageInfo_PlaintextSpec proto.InternalMessageInfo

type SymmetricSpec struct {
	// A non-secret identifier for a secret that is 'known' to Hoard (accessible via store or config)
	PublicID             string   `protobuf:"bytes,1,opt,name=PublicID,json=publicid,proto3" json:"publicid"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SymmetricSpec) Reset()         { *m = SymmetricSpec{} }
func (m *SymmetricSpec) String() string { return proto.CompactTextString(m) }
func (*SymmetricSpec) ProtoMessage()    {}
func (*SymmetricSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8d80872b3060482, []int{3}
}
func (m *SymmetricSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SymmetricSpec.Unmarshal(m, b)
}
func (m *SymmetricSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SymmetricSpec.Marshal(b, m, deterministic)
}
func (m *SymmetricSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SymmetricSpec.Merge(m, src)
}
func (m *SymmetricSpec) XXX_Size() int {
	return xxx_messageInfo_SymmetricSpec.Size(m)
}
func (m *SymmetricSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_SymmetricSpec.DiscardUnknown(m)
}

var xxx_messageInfo_SymmetricSpec proto.InternalMessageInfo

func (m *SymmetricSpec) GetPublicID() string {
	if m != nil {
		return m.PublicID
	}
	return ""
}

type OpenPGPSpec struct {
	PublicKey            string   `protobuf:"bytes,1,opt,name=PublicKey,json=publickey,proto3" json:"publickey"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenPGPSpec) Reset()         { *m = OpenPGPSpec{} }
func (m *OpenPGPSpec) String() string { return proto.CompactTextString(m) }
func (*OpenPGPSpec) ProtoMessage()    {}
func (*OpenPGPSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8d80872b3060482, []int{4}
}
func (m *OpenPGPSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenPGPSpec.Unmarshal(m, b)
}
func (m *OpenPGPSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenPGPSpec.Marshal(b, m, deterministic)
}
func (m *OpenPGPSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenPGPSpec.Merge(m, src)
}
func (m *OpenPGPSpec) XXX_Size() int {
	return xxx_messageInfo_OpenPGPSpec.Size(m)
}
func (m *OpenPGPSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenPGPSpec.DiscardUnknown(m)
}

var xxx_messageInfo_OpenPGPSpec proto.InternalMessageInfo

func (m *OpenPGPSpec) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func init() {
	proto.RegisterType((*Grant)(nil), "grant.Grant")
	proto.RegisterType((*Spec)(nil), "grant.Spec")
	proto.RegisterType((*PlaintextSpec)(nil), "grant.PlaintextSpec")
	proto.RegisterType((*SymmetricSpec)(nil), "grant.SymmetricSpec")
	proto.RegisterType((*OpenPGPSpec)(nil), "grant.OpenPGPSpec")
}

func init() { proto.RegisterFile("grant.proto", fileDescriptor_d8d80872b3060482) }

var fileDescriptor_d8d80872b3060482 = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcf, 0x4a, 0xf3, 0x40,
	0x14, 0xc5, 0xc9, 0xf7, 0xb5, 0xb6, 0x99, 0xb4, 0x08, 0x53, 0xc1, 0xe2, 0x26, 0x35, 0x20, 0x44,
	0xc4, 0x06, 0xea, 0xc6, 0xba, 0x33, 0x28, 0xa5, 0xb8, 0x30, 0x4c, 0xc1, 0x85, 0xbb, 0x24, 0x9d,
	0xa6, 0xc1, 0x66, 0x66, 0x98, 0xa4, 0xa5, 0x79, 0x1f, 0xdf, 0xc5, 0xb7, 0xc8, 0x03, 0xe4, 0x29,
	0xa4, 0x37, 0xff, 0x5a, 0x70, 0x13, 0xce, 0xfc, 0x2e, 0xe7, 0xcc, 0xb9, 0x61, 0x90, 0x16, 0x48,
	0x97, 0x25, 0x63, 0x21, 0x79, 0xc2, 0x71, 0x1b, 0x0e, 0x57, 0xf7, 0x41, 0x98, 0xac, 0xb7, 0xde,
	0xd8, 0xe7, 0x91, 0x15, 0xf0, 0x80, 0x5b, 0x30, 0xf5, 0xb6, 0x2b, 0x38, 0xc1, 0x01, 0x54, 0xe1,
	0x32, 0xbe, 0x15, 0xd4, 0x9e, 0x1d, 0x8c, 0xf8, 0x16, 0xb5, 0x16, 0x82, 0xfa, 0x43, 0x65, 0xa4,
	0x98, 0xda, 0x44, 0x1b, 0x17, 0xd9, 0x07, 0x64, 0x77, 0xf3, 0x4c, 0x6f, 0xc5, 0x82, 0xfa, 0x04,
	0xbe, 0x78, 0x8e, 0x06, 0xaf, 0xcc, 0x97, 0xa9, 0x48, 0xe8, 0x92, 0xd0, 0x15, 0x95, 0x94, 0xf9,
	0x34, 0x1e, 0xfe, 0x1b, 0x29, 0x66, 0xcf, 0xbe, 0xcc, 0x33, 0x7d, 0x40, 0xab, 0xb1, 0xac, 0xc7,
	0xe4, 0x2f, 0x88, 0x6f, 0x50, 0xe7, 0x83, 0xca, 0x38, 0xe4, 0x6c, 0xf8, 0x7f, 0xa4, 0x98, 0x6d,
	0x5b, 0xcb, 0x33, 0xbd, 0xb3, 0x2b, 0x10, 0xa9, 0x84, 0xf1, 0xa3, 0x14, 0xed, 0xf0, 0x33, 0x52,
	0x9d, 0x8d, 0x1b, 0xb2, 0x84, 0xee, 0x93, 0xb2, 0xea, 0x45, 0x59, 0xb5, 0xe6, 0xd0, 0xb9, 0x9f,
	0x67, 0xba, 0x2a, 0x2a, 0x44, 0x1a, 0x79, 0x88, 0x58, 0xa4, 0x51, 0x44, 0x13, 0x19, 0xfa, 0xd0,
	0xb9, 0x89, 0xa8, 0x79, 0x13, 0x11, 0x57, 0x88, 0x34, 0x12, 0x4f, 0x51, 0xe7, 0x5d, 0x50, 0xe6,
	0xcc, 0x1c, 0x68, 0xad, 0x4d, 0x70, 0x19, 0x50, 0x52, 0xb0, 0xc3, 0x26, 0x5c, 0x50, 0x26, 0x02,
	0x41, 0x2a, 0x61, 0x9c, 0xa3, 0xfe, 0x49, 0x51, 0x63, 0x8a, 0xfa, 0x27, 0xd7, 0x62, 0x13, 0x75,
	0x9d, 0xad, 0xb7, 0x09, 0xfd, 0xf9, 0x0b, 0x6c, 0xa8, 0xda, 0xbd, 0x3c, 0xd3, 0xbb, 0x02, 0x58,
	0xb8, 0x24, 0xb5, 0x32, 0x9e, 0x90, 0x76, 0x74, 0x21, 0xbe, 0x43, 0x6a, 0x61, 0x7c, 0xa3, 0x69,
	0xe9, 0x2c, 0xfe, 0x02, 0xc0, 0x2f, 0x9a, 0x92, 0x46, 0xda, 0xd7, 0x9f, 0xfa, 0xd1, 0x4b, 0x89,
	0x38, 0x73, 0xf7, 0xd6, 0x9a, 0xbb, 0x72, 0x69, 0xed, 0x1e, 0x2d, 0x58, 0xc6, 0x3b, 0x83, 0x27,
	0xf2, 0xf0, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xf1, 0xbc, 0x99, 0x4b, 0x67, 0x02, 0x00, 0x00,
}
