// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grant "github.com/monax/hoard/v7/grant"
	meta "github.com/monax/hoard/v7/meta"
	reference "github.com/monax/hoard/v7/reference"
	stores "github.com/monax/hoard/v7/stores"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GrantAndGrantSpec struct {
	Grant *grant.Grant `protobuf:"bytes,1,opt,name=Grant,proto3" json:"Grant,omitempty"`
	// The type of grant to output
	GrantSpec            *grant.Spec `protobuf:"bytes,2,opt,name=GrantSpec,proto3" json:"GrantSpec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GrantAndGrantSpec) Reset()         { *m = GrantAndGrantSpec{} }
func (m *GrantAndGrantSpec) String() string { return proto.CompactTextString(m) }
func (*GrantAndGrantSpec) ProtoMessage()    {}
func (*GrantAndGrantSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}
func (m *GrantAndGrantSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrantAndGrantSpec.Unmarshal(m, b)
}
func (m *GrantAndGrantSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrantAndGrantSpec.Marshal(b, m, deterministic)
}
func (m *GrantAndGrantSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrantAndGrantSpec.Merge(m, src)
}
func (m *GrantAndGrantSpec) XXX_Size() int {
	return xxx_messageInfo_GrantAndGrantSpec.Size(m)
}
func (m *GrantAndGrantSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_GrantAndGrantSpec.DiscardUnknown(m)
}

var xxx_messageInfo_GrantAndGrantSpec proto.InternalMessageInfo

func (m *GrantAndGrantSpec) GetGrant() *grant.Grant {
	if m != nil {
		return m.Grant
	}
	return nil
}

func (m *GrantAndGrantSpec) GetGrantSpec() *grant.Spec {
	if m != nil {
		return m.GrantSpec
	}
	return nil
}

type PlaintextAndGrantSpec struct {
	Plaintext *Plaintext `protobuf:"bytes,1,opt,name=Plaintext,proto3" json:"Plaintext,omitempty"`
	// The type of grant to output
	GrantSpec            *grant.Spec `protobuf:"bytes,2,opt,name=GrantSpec,proto3" json:"GrantSpec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PlaintextAndGrantSpec) Reset()         { *m = PlaintextAndGrantSpec{} }
func (m *PlaintextAndGrantSpec) String() string { return proto.CompactTextString(m) }
func (*PlaintextAndGrantSpec) ProtoMessage()    {}
func (*PlaintextAndGrantSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}
func (m *PlaintextAndGrantSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaintextAndGrantSpec.Unmarshal(m, b)
}
func (m *PlaintextAndGrantSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaintextAndGrantSpec.Marshal(b, m, deterministic)
}
func (m *PlaintextAndGrantSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaintextAndGrantSpec.Merge(m, src)
}
func (m *PlaintextAndGrantSpec) XXX_Size() int {
	return xxx_messageInfo_PlaintextAndGrantSpec.Size(m)
}
func (m *PlaintextAndGrantSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaintextAndGrantSpec.DiscardUnknown(m)
}

var xxx_messageInfo_PlaintextAndGrantSpec proto.InternalMessageInfo

func (m *PlaintextAndGrantSpec) GetPlaintext() *Plaintext {
	if m != nil {
		return m.Plaintext
	}
	return nil
}

func (m *PlaintextAndGrantSpec) GetGrantSpec() *grant.Spec {
	if m != nil {
		return m.GrantSpec
	}
	return nil
}

type PlaintextAndMeta struct {
	Meta                 *meta.Meta `protobuf:"bytes,1,opt,name=Meta,proto3" json:"Meta,omitempty"`
	Plaintext            *Plaintext `protobuf:"bytes,2,opt,name=Plaintext,proto3" json:"Plaintext,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PlaintextAndMeta) Reset()         { *m = PlaintextAndMeta{} }
func (m *PlaintextAndMeta) String() string { return proto.CompactTextString(m) }
func (*PlaintextAndMeta) ProtoMessage()    {}
func (*PlaintextAndMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}
func (m *PlaintextAndMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaintextAndMeta.Unmarshal(m, b)
}
func (m *PlaintextAndMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaintextAndMeta.Marshal(b, m, deterministic)
}
func (m *PlaintextAndMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaintextAndMeta.Merge(m, src)
}
func (m *PlaintextAndMeta) XXX_Size() int {
	return xxx_messageInfo_PlaintextAndMeta.Size(m)
}
func (m *PlaintextAndMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaintextAndMeta.DiscardUnknown(m)
}

var xxx_messageInfo_PlaintextAndMeta proto.InternalMessageInfo

func (m *PlaintextAndMeta) GetMeta() *meta.Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *PlaintextAndMeta) GetPlaintext() *Plaintext {
	if m != nil {
		return m.Plaintext
	}
	return nil
}

type PlaintextAndGrantSpecAndMeta struct {
	Meta                  *meta.Meta             `protobuf:"bytes,1,opt,name=Meta,proto3" json:"Meta,omitempty"`
	PlaintextAndGrantSpec *PlaintextAndGrantSpec `protobuf:"bytes,2,opt,name=PlaintextAndGrantSpec,proto3" json:"PlaintextAndGrantSpec,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}               `json:"-"`
	XXX_unrecognized      []byte                 `json:"-"`
	XXX_sizecache         int32                  `json:"-"`
}

func (m *PlaintextAndGrantSpecAndMeta) Reset()         { *m = PlaintextAndGrantSpecAndMeta{} }
func (m *PlaintextAndGrantSpecAndMeta) String() string { return proto.CompactTextString(m) }
func (*PlaintextAndGrantSpecAndMeta) ProtoMessage()    {}
func (*PlaintextAndGrantSpecAndMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}
func (m *PlaintextAndGrantSpecAndMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaintextAndGrantSpecAndMeta.Unmarshal(m, b)
}
func (m *PlaintextAndGrantSpecAndMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaintextAndGrantSpecAndMeta.Marshal(b, m, deterministic)
}
func (m *PlaintextAndGrantSpecAndMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaintextAndGrantSpecAndMeta.Merge(m, src)
}
func (m *PlaintextAndGrantSpecAndMeta) XXX_Size() int {
	return xxx_messageInfo_PlaintextAndGrantSpecAndMeta.Size(m)
}
func (m *PlaintextAndGrantSpecAndMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaintextAndGrantSpecAndMeta.DiscardUnknown(m)
}

var xxx_messageInfo_PlaintextAndGrantSpecAndMeta proto.InternalMessageInfo

func (m *PlaintextAndGrantSpecAndMeta) GetMeta() *meta.Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *PlaintextAndGrantSpecAndMeta) GetPlaintextAndGrantSpec() *PlaintextAndGrantSpec {
	if m != nil {
		return m.PlaintextAndGrantSpec
	}
	return nil
}

type ReferenceAndGrantSpec struct {
	Reference *reference.Ref `protobuf:"bytes,1,opt,name=Reference,proto3" json:"Reference,omitempty"`
	// The type of grant to output
	GrantSpec            *grant.Spec `protobuf:"bytes,2,opt,name=GrantSpec,proto3" json:"GrantSpec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReferenceAndGrantSpec) Reset()         { *m = ReferenceAndGrantSpec{} }
func (m *ReferenceAndGrantSpec) String() string { return proto.CompactTextString(m) }
func (*ReferenceAndGrantSpec) ProtoMessage()    {}
func (*ReferenceAndGrantSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}
func (m *ReferenceAndGrantSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReferenceAndGrantSpec.Unmarshal(m, b)
}
func (m *ReferenceAndGrantSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReferenceAndGrantSpec.Marshal(b, m, deterministic)
}
func (m *ReferenceAndGrantSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReferenceAndGrantSpec.Merge(m, src)
}
func (m *ReferenceAndGrantSpec) XXX_Size() int {
	return xxx_messageInfo_ReferenceAndGrantSpec.Size(m)
}
func (m *ReferenceAndGrantSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ReferenceAndGrantSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ReferenceAndGrantSpec proto.InternalMessageInfo

func (m *ReferenceAndGrantSpec) GetReference() *reference.Ref {
	if m != nil {
		return m.Reference
	}
	return nil
}

func (m *ReferenceAndGrantSpec) GetGrantSpec() *grant.Spec {
	if m != nil {
		return m.GrantSpec
	}
	return nil
}

type Plaintext struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	Salt                 []byte   `protobuf:"bytes,2,opt,name=Salt,proto3" json:"Salt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Plaintext) Reset()         { *m = Plaintext{} }
func (m *Plaintext) String() string { return proto.CompactTextString(m) }
func (*Plaintext) ProtoMessage()    {}
func (*Plaintext) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}
func (m *Plaintext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plaintext.Unmarshal(m, b)
}
func (m *Plaintext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plaintext.Marshal(b, m, deterministic)
}
func (m *Plaintext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plaintext.Merge(m, src)
}
func (m *Plaintext) XXX_Size() int {
	return xxx_messageInfo_Plaintext.Size(m)
}
func (m *Plaintext) XXX_DiscardUnknown() {
	xxx_messageInfo_Plaintext.DiscardUnknown(m)
}

var xxx_messageInfo_Plaintext proto.InternalMessageInfo

func (m *Plaintext) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Plaintext) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

type Ciphertext struct {
	EncryptedData        []byte   `protobuf:"bytes,1,opt,name=EncryptedData,proto3" json:"EncryptedData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ciphertext) Reset()         { *m = Ciphertext{} }
func (m *Ciphertext) String() string { return proto.CompactTextString(m) }
func (*Ciphertext) ProtoMessage()    {}
func (*Ciphertext) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}
func (m *Ciphertext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ciphertext.Unmarshal(m, b)
}
func (m *Ciphertext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ciphertext.Marshal(b, m, deterministic)
}
func (m *Ciphertext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ciphertext.Merge(m, src)
}
func (m *Ciphertext) XXX_Size() int {
	return xxx_messageInfo_Ciphertext.Size(m)
}
func (m *Ciphertext) XXX_DiscardUnknown() {
	xxx_messageInfo_Ciphertext.DiscardUnknown(m)
}

var xxx_messageInfo_Ciphertext proto.InternalMessageInfo

func (m *Ciphertext) GetEncryptedData() []byte {
	if m != nil {
		return m.EncryptedData
	}
	return nil
}

type ReferenceAndCiphertext struct {
	Reference            *reference.Ref `protobuf:"bytes,1,opt,name=Reference,proto3" json:"Reference,omitempty"`
	Ciphertext           *Ciphertext    `protobuf:"bytes,2,opt,name=Ciphertext,proto3" json:"Ciphertext,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReferenceAndCiphertext) Reset()         { *m = ReferenceAndCiphertext{} }
func (m *ReferenceAndCiphertext) String() string { return proto.CompactTextString(m) }
func (*ReferenceAndCiphertext) ProtoMessage()    {}
func (*ReferenceAndCiphertext) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}
func (m *ReferenceAndCiphertext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReferenceAndCiphertext.Unmarshal(m, b)
}
func (m *ReferenceAndCiphertext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReferenceAndCiphertext.Marshal(b, m, deterministic)
}
func (m *ReferenceAndCiphertext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReferenceAndCiphertext.Merge(m, src)
}
func (m *ReferenceAndCiphertext) XXX_Size() int {
	return xxx_messageInfo_ReferenceAndCiphertext.Size(m)
}
func (m *ReferenceAndCiphertext) XXX_DiscardUnknown() {
	xxx_messageInfo_ReferenceAndCiphertext.DiscardUnknown(m)
}

var xxx_messageInfo_ReferenceAndCiphertext proto.InternalMessageInfo

func (m *ReferenceAndCiphertext) GetReference() *reference.Ref {
	if m != nil {
		return m.Reference
	}
	return nil
}

func (m *ReferenceAndCiphertext) GetCiphertext() *Ciphertext {
	if m != nil {
		return m.Ciphertext
	}
	return nil
}

type Address struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}
func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func init() {
	proto.RegisterType((*GrantAndGrantSpec)(nil), "api.GrantAndGrantSpec")
	proto.RegisterType((*PlaintextAndGrantSpec)(nil), "api.PlaintextAndGrantSpec")
	proto.RegisterType((*PlaintextAndMeta)(nil), "api.PlaintextAndMeta")
	proto.RegisterType((*PlaintextAndGrantSpecAndMeta)(nil), "api.PlaintextAndGrantSpecAndMeta")
	proto.RegisterType((*ReferenceAndGrantSpec)(nil), "api.ReferenceAndGrantSpec")
	proto.RegisterType((*Plaintext)(nil), "api.Plaintext")
	proto.RegisterType((*Ciphertext)(nil), "api.Ciphertext")
	proto.RegisterType((*ReferenceAndCiphertext)(nil), "api.ReferenceAndCiphertext")
	proto.RegisterType((*Address)(nil), "api.Address")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 626 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x55, 0xb6, 0xd0, 0xd2, 0xbb, 0xc0, 0x86, 0xa5, 0x4d, 0x53, 0xf8, 0x0e, 0xd3, 0x56, 0x3e,
	0x94, 0x96, 0x4e, 0x08, 0x24, 0x9e, 0xc6, 0x8a, 0x26, 0x1e, 0x90, 0x22, 0x57, 0x7b, 0x41, 0x42,
	0xc2, 0x6b, 0xee, 0xd6, 0x48, 0x69, 0x12, 0x25, 0x0e, 0x1b, 0x3c, 0xf1, 0x13, 0xf8, 0x0b, 0x3c,
	0xf2, 0x2f, 0x91, 0x1d, 0x37, 0x1f, 0x4e, 0x07, 0xf4, 0xa9, 0xf6, 0xf1, 0x39, 0xbe, 0xf7, 0x9e,
	0x7b, 0x9d, 0x42, 0x8f, 0x25, 0x81, 0x9b, 0xa4, 0x31, 0x8f, 0xc9, 0x3a, 0x4b, 0x02, 0x7b, 0xe3,
	0x22, 0x65, 0x11, 0x2f, 0x10, 0x1b, 0xe6, 0xc8, 0x99, 0x5a, 0x6f, 0xa6, 0x78, 0x8e, 0x29, 0x46,
	0x53, 0x54, 0x80, 0x95, 0xf1, 0x38, 0xc5, 0xac, 0xd8, 0x39, 0x67, 0x70, 0xe7, 0x44, 0x28, 0x8f,
	0x22, 0x5f, 0xfe, 0x4e, 0x12, 0x9c, 0x12, 0x07, 0x6e, 0xc8, 0xcd, 0xae, 0xf1, 0xc8, 0xe8, 0x6f,
	0x8c, 0x2c, 0xb7, 0xb8, 0x5c, 0x62, 0xb4, 0x38, 0x22, 0x4f, 0xa1, 0x57, 0x0a, 0x76, 0xd7, 0x24,
	0x6f, 0x43, 0xf1, 0x04, 0x44, 0xab, 0x53, 0x27, 0x81, 0x6d, 0x2f, 0x64, 0x41, 0xc4, 0xf1, 0xaa,
	0x19, 0xe7, 0x05, 0xf4, 0xca, 0x03, 0x15, 0xeb, 0xb6, 0x2b, 0x0a, 0x2b, 0x51, 0x5a, 0x11, 0x56,
	0x89, 0xf8, 0x05, 0xb6, 0xea, 0x11, 0x3f, 0x22, 0x67, 0xe4, 0x01, 0x98, 0xe2, 0x57, 0xc5, 0x01,
	0x57, 0x7a, 0x24, 0x10, 0x2a, 0xf1, 0x66, 0x32, 0x6b, 0xff, 0x48, 0xc6, 0xf9, 0x69, 0xc0, 0xbd,
	0xa5, 0x45, 0xfd, 0x6f, 0x38, 0xef, 0x1a, 0x53, 0x54, 0x68, 0xbb, 0x19, 0xba, 0xce, 0xa0, 0xcb,
	0x85, 0xc2, 0x66, 0xba, 0xe8, 0xb5, 0x6e, 0x73, 0x79, 0x50, 0xda, 0x5c, 0x8d, 0x05, 0xc5, 0x73,
	0x5a, 0x11, 0x56, 0xb1, 0xf9, 0xb0, 0x66, 0x19, 0x21, 0x60, 0x8e, 0x99, 0x2a, 0xd8, 0xa2, 0x72,
	0x2d, 0xb0, 0x09, 0x0b, 0x0b, 0x3b, 0x2d, 0x2a, 0xd7, 0xce, 0x08, 0xe0, 0x38, 0x48, 0x66, 0x98,
	0x4a, 0xd5, 0x1e, 0xdc, 0x7a, 0x1f, 0x4d, 0xd3, 0x6f, 0x09, 0x47, 0xbf, 0x26, 0x6f, 0x82, 0xce,
	0x25, 0xec, 0xd4, 0x4b, 0xab, 0xe9, 0x57, 0xab, 0x6d, 0x50, 0x8f, 0xad, 0x8a, 0xdb, 0x94, 0x4e,
	0x57, 0x30, 0xad, 0x51, 0x9c, 0x27, 0xd0, 0x3d, 0xf2, 0xfd, 0x14, 0xb3, 0x8c, 0xec, 0x96, 0x4b,
	0x95, 0xe3, 0x62, 0x3b, 0xfa, 0xb5, 0xa6, 0xde, 0x0b, 0x19, 0x82, 0x39, 0x41, 0x16, 0x92, 0xa2,
	0x7b, 0x4b, 0xbb, 0x61, 0x37, 0x5e, 0x13, 0xd9, 0x87, 0xce, 0x69, 0x94, 0x09, 0x4d, 0x03, 0xb7,
	0xb5, 0x22, 0x88, 0x0b, 0x1d, 0x8a, 0x92, 0xb7, 0x23, 0xef, 0x6e, 0x3d, 0x5a, 0xed, 0xde, 0x57,
	0xd0, 0xf5, 0x72, 0x5e, 0x4b, 0x66, 0xe9, 0xcc, 0x34, 0x45, 0x7d, 0x83, 0x3c, 0x87, 0x5e, 0x91,
	0xce, 0x09, 0xf2, 0x56, 0x46, 0x8d, 0x6b, 0x86, 0x06, 0x79, 0x06, 0x56, 0x41, 0x1e, 0x63, 0x88,
	0x1c, 0x35, 0xbe, 0x25, 0xf9, 0x0b, 0x8f, 0x3e, 0x43, 0xef, 0x38, 0x44, 0x56, 0x34, 0xed, 0x00,
	0xd6, 0xbd, 0x9c, 0x13, 0xed, 0x46, 0xbd, 0xe6, 0xbe, 0x21, 0x88, 0x22, 0x11, 0xed, 0xa0, 0x9d,
	0xca, 0xe8, 0x87, 0x01, 0xa0, 0x46, 0x26, 0x88, 0x23, 0xf2, 0x06, 0xba, 0x6a, 0xd7, 0x0a, 0x72,
	0xb7, 0xd5, 0x9a, 0xaa, 0xdd, 0x7d, 0x43, 0x28, 0xc7, 0x58, 0x28, 0xff, 0xc6, 0x5c, 0x92, 0xc2,
	0x6f, 0x03, 0xba, 0x13, 0x1e, 0xa7, 0xec, 0x02, 0xc9, 0x01, 0x98, 0x5e, 0x9e, 0xcd, 0x88, 0x3e,
	0x5b, 0x4d, 0x53, 0x64, 0x81, 0xa6, 0x97, 0x87, 0xa2, 0xf9, 0x35, 0xdc, 0xd6, 0x65, 0x43, 0x83,
	0xec, 0x83, 0x39, 0xe1, 0x8c, 0x6b, 0xc4, 0x2d, 0x57, 0x7d, 0xcc, 0xc5, 0xd9, 0x87, 0xe8, 0x3c,
	0x26, 0x7b, 0xd0, 0x29, 0xbb, 0x51, 0x67, 0x36, 0xbb, 0xf1, 0x1d, 0x6e, 0x8e, 0xe3, 0x69, 0x3e,
	0xc7, 0x88, 0x93, 0x97, 0x62, 0x7d, 0x19, 0x85, 0x31, 0xf3, 0xb5, 0x0e, 0x6e, 0xb7, 0x06, 0x47,
	0x7c, 0xb9, 0x86, 0x06, 0x79, 0x0b, 0x9d, 0xd3, 0x44, 0x0a, 0x1e, 0x5f, 0x3f, 0x5b, 0x8a, 0xae,
	0x8f, 0xd8, 0xbb, 0x87, 0x9f, 0xee, 0x5f, 0x04, 0x7c, 0x96, 0x9f, 0xb9, 0xd3, 0x78, 0x3e, 0x98,
	0xc7, 0x11, 0xbb, 0x1a, 0xcc, 0x62, 0x96, 0xfa, 0x83, 0xaf, 0xaf, 0x07, 0x2c, 0x09, 0xce, 0x3a,
	0xf2, 0x9f, 0xe9, 0xf0, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xed, 0xb6, 0x39, 0x5d, 0xe3, 0x06,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GrantClient is the client API for Grant service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrantClient interface {
	// Seal a Reference to create a Grant
	Seal(ctx context.Context, in *ReferenceAndGrantSpec, opts ...grpc.CallOption) (*grant.Grant, error)
	// Unseal a Grant to recover the Reference
	Unseal(ctx context.Context, in *grant.Grant, opts ...grpc.CallOption) (*reference.Ref, error)
	// Convert one grant to another grant to re-share with another party or just
	// to change grant type
	Reseal(ctx context.Context, in *GrantAndGrantSpec, opts ...grpc.CallOption) (*grant.Grant, error)
	// Put a Plaintext and returned the sealed Reference as a Grant
	PutSeal(ctx context.Context, opts ...grpc.CallOption) (Grant_PutSealClient, error)
	// Unseal a Grant and follow the Reference to return a Plaintext
	UnsealGet(ctx context.Context, in *grant.Grant, opts ...grpc.CallOption) (Grant_UnsealGetClient, error)
	// Unseal a Grant and follow the Reference to delete the Plaintext
	UnsealDelete(ctx context.Context, in *grant.Grant, opts ...grpc.CallOption) (*Address, error)
}

type grantClient struct {
	cc *grpc.ClientConn
}

func NewGrantClient(cc *grpc.ClientConn) GrantClient {
	return &grantClient{cc}
}

func (c *grantClient) Seal(ctx context.Context, in *ReferenceAndGrantSpec, opts ...grpc.CallOption) (*grant.Grant, error) {
	out := new(grant.Grant)
	err := c.cc.Invoke(ctx, "/api.Grant/Seal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grantClient) Unseal(ctx context.Context, in *grant.Grant, opts ...grpc.CallOption) (*reference.Ref, error) {
	out := new(reference.Ref)
	err := c.cc.Invoke(ctx, "/api.Grant/Unseal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grantClient) Reseal(ctx context.Context, in *GrantAndGrantSpec, opts ...grpc.CallOption) (*grant.Grant, error) {
	out := new(grant.Grant)
	err := c.cc.Invoke(ctx, "/api.Grant/Reseal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grantClient) PutSeal(ctx context.Context, opts ...grpc.CallOption) (Grant_PutSealClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Grant_serviceDesc.Streams[0], "/api.Grant/PutSeal", opts...)
	if err != nil {
		return nil, err
	}
	x := &grantPutSealClient{stream}
	return x, nil
}

type Grant_PutSealClient interface {
	Send(*PlaintextAndGrantSpec) error
	CloseAndRecv() (*grant.Grant, error)
	grpc.ClientStream
}

type grantPutSealClient struct {
	grpc.ClientStream
}

func (x *grantPutSealClient) Send(m *PlaintextAndGrantSpec) error {
	return x.ClientStream.SendMsg(m)
}

func (x *grantPutSealClient) CloseAndRecv() (*grant.Grant, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(grant.Grant)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *grantClient) UnsealGet(ctx context.Context, in *grant.Grant, opts ...grpc.CallOption) (Grant_UnsealGetClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Grant_serviceDesc.Streams[1], "/api.Grant/UnsealGet", opts...)
	if err != nil {
		return nil, err
	}
	x := &grantUnsealGetClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Grant_UnsealGetClient interface {
	Recv() (*Plaintext, error)
	grpc.ClientStream
}

type grantUnsealGetClient struct {
	grpc.ClientStream
}

func (x *grantUnsealGetClient) Recv() (*Plaintext, error) {
	m := new(Plaintext)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *grantClient) UnsealDelete(ctx context.Context, in *grant.Grant, opts ...grpc.CallOption) (*Address, error) {
	out := new(Address)
	err := c.cc.Invoke(ctx, "/api.Grant/UnsealDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrantServer is the server API for Grant service.
type GrantServer interface {
	// Seal a Reference to create a Grant
	Seal(context.Context, *ReferenceAndGrantSpec) (*grant.Grant, error)
	// Unseal a Grant to recover the Reference
	Unseal(context.Context, *grant.Grant) (*reference.Ref, error)
	// Convert one grant to another grant to re-share with another party or just
	// to change grant type
	Reseal(context.Context, *GrantAndGrantSpec) (*grant.Grant, error)
	// Put a Plaintext and returned the sealed Reference as a Grant
	PutSeal(Grant_PutSealServer) error
	// Unseal a Grant and follow the Reference to return a Plaintext
	UnsealGet(*grant.Grant, Grant_UnsealGetServer) error
	// Unseal a Grant and follow the Reference to delete the Plaintext
	UnsealDelete(context.Context, *grant.Grant) (*Address, error)
}

// UnimplementedGrantServer can be embedded to have forward compatible implementations.
type UnimplementedGrantServer struct {
}

func (*UnimplementedGrantServer) Seal(ctx context.Context, req *ReferenceAndGrantSpec) (*grant.Grant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Seal not implemented")
}
func (*UnimplementedGrantServer) Unseal(ctx context.Context, req *grant.Grant) (*reference.Ref, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unseal not implemented")
}
func (*UnimplementedGrantServer) Reseal(ctx context.Context, req *GrantAndGrantSpec) (*grant.Grant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reseal not implemented")
}
func (*UnimplementedGrantServer) PutSeal(srv Grant_PutSealServer) error {
	return status.Errorf(codes.Unimplemented, "method PutSeal not implemented")
}
func (*UnimplementedGrantServer) UnsealGet(req *grant.Grant, srv Grant_UnsealGetServer) error {
	return status.Errorf(codes.Unimplemented, "method UnsealGet not implemented")
}
func (*UnimplementedGrantServer) UnsealDelete(ctx context.Context, req *grant.Grant) (*Address, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnsealDelete not implemented")
}

func RegisterGrantServer(s *grpc.Server, srv GrantServer) {
	s.RegisterService(&_Grant_serviceDesc, srv)
}

func _Grant_Seal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReferenceAndGrantSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrantServer).Seal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Grant/Seal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrantServer).Seal(ctx, req.(*ReferenceAndGrantSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grant_Unseal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(grant.Grant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrantServer).Unseal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Grant/Unseal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrantServer).Unseal(ctx, req.(*grant.Grant))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grant_Reseal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantAndGrantSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrantServer).Reseal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Grant/Reseal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrantServer).Reseal(ctx, req.(*GrantAndGrantSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grant_PutSeal_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GrantServer).PutSeal(&grantPutSealServer{stream})
}

type Grant_PutSealServer interface {
	SendAndClose(*grant.Grant) error
	Recv() (*PlaintextAndGrantSpec, error)
	grpc.ServerStream
}

type grantPutSealServer struct {
	grpc.ServerStream
}

func (x *grantPutSealServer) SendAndClose(m *grant.Grant) error {
	return x.ServerStream.SendMsg(m)
}

func (x *grantPutSealServer) Recv() (*PlaintextAndGrantSpec, error) {
	m := new(PlaintextAndGrantSpec)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Grant_UnsealGet_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(grant.Grant)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GrantServer).UnsealGet(m, &grantUnsealGetServer{stream})
}

type Grant_UnsealGetServer interface {
	Send(*Plaintext) error
	grpc.ServerStream
}

type grantUnsealGetServer struct {
	grpc.ServerStream
}

func (x *grantUnsealGetServer) Send(m *Plaintext) error {
	return x.ServerStream.SendMsg(m)
}

func _Grant_UnsealDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(grant.Grant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrantServer).UnsealDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Grant/UnsealDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrantServer).UnsealDelete(ctx, req.(*grant.Grant))
	}
	return interceptor(ctx, in, info, handler)
}

var _Grant_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Grant",
	HandlerType: (*GrantServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Seal",
			Handler:    _Grant_Seal_Handler,
		},
		{
			MethodName: "Unseal",
			Handler:    _Grant_Unseal_Handler,
		},
		{
			MethodName: "Reseal",
			Handler:    _Grant_Reseal_Handler,
		},
		{
			MethodName: "UnsealDelete",
			Handler:    _Grant_UnsealDelete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PutSeal",
			Handler:       _Grant_PutSeal_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "UnsealGet",
			Handler:       _Grant_UnsealGet_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}

// CleartextClient is the client API for Cleartext service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CleartextClient interface {
	// Push some plaintext data into storage and get its deterministically
	// generated secret reference.
	Put(ctx context.Context, opts ...grpc.CallOption) (Cleartext_PutClient, error)
	// Provide a secret reference to an encrypted blob and get the plaintext
	// data back.
	Get(ctx context.Context, in *reference.Ref, opts ...grpc.CallOption) (Cleartext_GetClient, error)
}

type cleartextClient struct {
	cc *grpc.ClientConn
}

func NewCleartextClient(cc *grpc.ClientConn) CleartextClient {
	return &cleartextClient{cc}
}

func (c *cleartextClient) Put(ctx context.Context, opts ...grpc.CallOption) (Cleartext_PutClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Cleartext_serviceDesc.Streams[0], "/api.Cleartext/Put", opts...)
	if err != nil {
		return nil, err
	}
	x := &cleartextPutClient{stream}
	return x, nil
}

type Cleartext_PutClient interface {
	Send(*Plaintext) error
	CloseAndRecv() (*reference.Ref, error)
	grpc.ClientStream
}

type cleartextPutClient struct {
	grpc.ClientStream
}

func (x *cleartextPutClient) Send(m *Plaintext) error {
	return x.ClientStream.SendMsg(m)
}

func (x *cleartextPutClient) CloseAndRecv() (*reference.Ref, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(reference.Ref)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cleartextClient) Get(ctx context.Context, in *reference.Ref, opts ...grpc.CallOption) (Cleartext_GetClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Cleartext_serviceDesc.Streams[1], "/api.Cleartext/Get", opts...)
	if err != nil {
		return nil, err
	}
	x := &cleartextGetClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Cleartext_GetClient interface {
	Recv() (*Plaintext, error)
	grpc.ClientStream
}

type cleartextGetClient struct {
	grpc.ClientStream
}

func (x *cleartextGetClient) Recv() (*Plaintext, error) {
	m := new(Plaintext)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CleartextServer is the server API for Cleartext service.
type CleartextServer interface {
	// Push some plaintext data into storage and get its deterministically
	// generated secret reference.
	Put(Cleartext_PutServer) error
	// Provide a secret reference to an encrypted blob and get the plaintext
	// data back.
	Get(*reference.Ref, Cleartext_GetServer) error
}

// UnimplementedCleartextServer can be embedded to have forward compatible implementations.
type UnimplementedCleartextServer struct {
}

func (*UnimplementedCleartextServer) Put(srv Cleartext_PutServer) error {
	return status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (*UnimplementedCleartextServer) Get(req *reference.Ref, srv Cleartext_GetServer) error {
	return status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterCleartextServer(s *grpc.Server, srv CleartextServer) {
	s.RegisterService(&_Cleartext_serviceDesc, srv)
}

func _Cleartext_Put_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CleartextServer).Put(&cleartextPutServer{stream})
}

type Cleartext_PutServer interface {
	SendAndClose(*reference.Ref) error
	Recv() (*Plaintext, error)
	grpc.ServerStream
}

type cleartextPutServer struct {
	grpc.ServerStream
}

func (x *cleartextPutServer) SendAndClose(m *reference.Ref) error {
	return x.ServerStream.SendMsg(m)
}

func (x *cleartextPutServer) Recv() (*Plaintext, error) {
	m := new(Plaintext)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Cleartext_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(reference.Ref)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CleartextServer).Get(m, &cleartextGetServer{stream})
}

type Cleartext_GetServer interface {
	Send(*Plaintext) error
	grpc.ServerStream
}

type cleartextGetServer struct {
	grpc.ServerStream
}

func (x *cleartextGetServer) Send(m *Plaintext) error {
	return x.ServerStream.SendMsg(m)
}

var _Cleartext_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Cleartext",
	HandlerType: (*CleartextServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Put",
			Handler:       _Cleartext_Put_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Get",
			Handler:       _Cleartext_Get_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}

// EncryptionClient is the client API for Encryption service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EncryptionClient interface {
	// Encrypt some data and get its deterministically generated
	// secret reference including its address without storing the data.
	Encrypt(ctx context.Context, opts ...grpc.CallOption) (Encryption_EncryptClient, error)
	// Decrypt the provided data by supplying it alongside its secret
	// reference. The address is not used for decryption and may be omitted.
	Decrypt(ctx context.Context, in *ReferenceAndCiphertext, opts ...grpc.CallOption) (Encryption_DecryptClient, error)
}

type encryptionClient struct {
	cc *grpc.ClientConn
}

func NewEncryptionClient(cc *grpc.ClientConn) EncryptionClient {
	return &encryptionClient{cc}
}

func (c *encryptionClient) Encrypt(ctx context.Context, opts ...grpc.CallOption) (Encryption_EncryptClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Encryption_serviceDesc.Streams[0], "/api.Encryption/Encrypt", opts...)
	if err != nil {
		return nil, err
	}
	x := &encryptionEncryptClient{stream}
	return x, nil
}

type Encryption_EncryptClient interface {
	Send(*Plaintext) error
	CloseAndRecv() (*ReferenceAndCiphertext, error)
	grpc.ClientStream
}

type encryptionEncryptClient struct {
	grpc.ClientStream
}

func (x *encryptionEncryptClient) Send(m *Plaintext) error {
	return x.ClientStream.SendMsg(m)
}

func (x *encryptionEncryptClient) CloseAndRecv() (*ReferenceAndCiphertext, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ReferenceAndCiphertext)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *encryptionClient) Decrypt(ctx context.Context, in *ReferenceAndCiphertext, opts ...grpc.CallOption) (Encryption_DecryptClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Encryption_serviceDesc.Streams[1], "/api.Encryption/Decrypt", opts...)
	if err != nil {
		return nil, err
	}
	x := &encryptionDecryptClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Encryption_DecryptClient interface {
	Recv() (*Plaintext, error)
	grpc.ClientStream
}

type encryptionDecryptClient struct {
	grpc.ClientStream
}

func (x *encryptionDecryptClient) Recv() (*Plaintext, error) {
	m := new(Plaintext)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EncryptionServer is the server API for Encryption service.
type EncryptionServer interface {
	// Encrypt some data and get its deterministically generated
	// secret reference including its address without storing the data.
	Encrypt(Encryption_EncryptServer) error
	// Decrypt the provided data by supplying it alongside its secret
	// reference. The address is not used for decryption and may be omitted.
	Decrypt(*ReferenceAndCiphertext, Encryption_DecryptServer) error
}

// UnimplementedEncryptionServer can be embedded to have forward compatible implementations.
type UnimplementedEncryptionServer struct {
}

func (*UnimplementedEncryptionServer) Encrypt(srv Encryption_EncryptServer) error {
	return status.Errorf(codes.Unimplemented, "method Encrypt not implemented")
}
func (*UnimplementedEncryptionServer) Decrypt(req *ReferenceAndCiphertext, srv Encryption_DecryptServer) error {
	return status.Errorf(codes.Unimplemented, "method Decrypt not implemented")
}

func RegisterEncryptionServer(s *grpc.Server, srv EncryptionServer) {
	s.RegisterService(&_Encryption_serviceDesc, srv)
}

func _Encryption_Encrypt_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EncryptionServer).Encrypt(&encryptionEncryptServer{stream})
}

type Encryption_EncryptServer interface {
	SendAndClose(*ReferenceAndCiphertext) error
	Recv() (*Plaintext, error)
	grpc.ServerStream
}

type encryptionEncryptServer struct {
	grpc.ServerStream
}

func (x *encryptionEncryptServer) SendAndClose(m *ReferenceAndCiphertext) error {
	return x.ServerStream.SendMsg(m)
}

func (x *encryptionEncryptServer) Recv() (*Plaintext, error) {
	m := new(Plaintext)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Encryption_Decrypt_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReferenceAndCiphertext)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EncryptionServer).Decrypt(m, &encryptionDecryptServer{stream})
}

type Encryption_DecryptServer interface {
	Send(*Plaintext) error
	grpc.ServerStream
}

type encryptionDecryptServer struct {
	grpc.ServerStream
}

func (x *encryptionDecryptServer) Send(m *Plaintext) error {
	return x.ServerStream.SendMsg(m)
}

var _Encryption_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Encryption",
	HandlerType: (*EncryptionServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Encrypt",
			Handler:       _Encryption_Encrypt_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Decrypt",
			Handler:       _Encryption_Decrypt_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}

// StorageClient is the client API for Storage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorageClient interface {
	// Insert the (presumably) encrypted data provided and get the its address.
	Push(ctx context.Context, opts ...grpc.CallOption) (Storage_PushClient, error)
	// Retrieve the (presumably) encrypted data stored at address.
	Pull(ctx context.Context, in *Address, opts ...grpc.CallOption) (Storage_PullClient, error)
	// Get some information about the encrypted blob stored at an address,
	// including whether it exists.
	Stat(ctx context.Context, in *Address, opts ...grpc.CallOption) (*stores.StatInfo, error)
	// Delete the encrypted blob stored at address
	Delete(ctx context.Context, in *Address, opts ...grpc.CallOption) (*Address, error)
}

type storageClient struct {
	cc *grpc.ClientConn
}

func NewStorageClient(cc *grpc.ClientConn) StorageClient {
	return &storageClient{cc}
}

func (c *storageClient) Push(ctx context.Context, opts ...grpc.CallOption) (Storage_PushClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Storage_serviceDesc.Streams[0], "/api.Storage/Push", opts...)
	if err != nil {
		return nil, err
	}
	x := &storagePushClient{stream}
	return x, nil
}

type Storage_PushClient interface {
	Send(*Ciphertext) error
	CloseAndRecv() (*Address, error)
	grpc.ClientStream
}

type storagePushClient struct {
	grpc.ClientStream
}

func (x *storagePushClient) Send(m *Ciphertext) error {
	return x.ClientStream.SendMsg(m)
}

func (x *storagePushClient) CloseAndRecv() (*Address, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Address)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storageClient) Pull(ctx context.Context, in *Address, opts ...grpc.CallOption) (Storage_PullClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Storage_serviceDesc.Streams[1], "/api.Storage/Pull", opts...)
	if err != nil {
		return nil, err
	}
	x := &storagePullClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Storage_PullClient interface {
	Recv() (*Ciphertext, error)
	grpc.ClientStream
}

type storagePullClient struct {
	grpc.ClientStream
}

func (x *storagePullClient) Recv() (*Ciphertext, error) {
	m := new(Ciphertext)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storageClient) Stat(ctx context.Context, in *Address, opts ...grpc.CallOption) (*stores.StatInfo, error) {
	out := new(stores.StatInfo)
	err := c.cc.Invoke(ctx, "/api.Storage/Stat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) Delete(ctx context.Context, in *Address, opts ...grpc.CallOption) (*Address, error) {
	out := new(Address)
	err := c.cc.Invoke(ctx, "/api.Storage/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServer is the server API for Storage service.
type StorageServer interface {
	// Insert the (presumably) encrypted data provided and get the its address.
	Push(Storage_PushServer) error
	// Retrieve the (presumably) encrypted data stored at address.
	Pull(*Address, Storage_PullServer) error
	// Get some information about the encrypted blob stored at an address,
	// including whether it exists.
	Stat(context.Context, *Address) (*stores.StatInfo, error)
	// Delete the encrypted blob stored at address
	Delete(context.Context, *Address) (*Address, error)
}

// UnimplementedStorageServer can be embedded to have forward compatible implementations.
type UnimplementedStorageServer struct {
}

func (*UnimplementedStorageServer) Push(srv Storage_PushServer) error {
	return status.Errorf(codes.Unimplemented, "method Push not implemented")
}
func (*UnimplementedStorageServer) Pull(req *Address, srv Storage_PullServer) error {
	return status.Errorf(codes.Unimplemented, "method Pull not implemented")
}
func (*UnimplementedStorageServer) Stat(ctx context.Context, req *Address) (*stores.StatInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stat not implemented")
}
func (*UnimplementedStorageServer) Delete(ctx context.Context, req *Address) (*Address, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterStorageServer(s *grpc.Server, srv StorageServer) {
	s.RegisterService(&_Storage_serviceDesc, srv)
}

func _Storage_Push_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StorageServer).Push(&storagePushServer{stream})
}

type Storage_PushServer interface {
	SendAndClose(*Address) error
	Recv() (*Ciphertext, error)
	grpc.ServerStream
}

type storagePushServer struct {
	grpc.ServerStream
}

func (x *storagePushServer) SendAndClose(m *Address) error {
	return x.ServerStream.SendMsg(m)
}

func (x *storagePushServer) Recv() (*Ciphertext, error) {
	m := new(Ciphertext)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Storage_Pull_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Address)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageServer).Pull(m, &storagePullServer{stream})
}

type Storage_PullServer interface {
	Send(*Ciphertext) error
	grpc.ServerStream
}

type storagePullServer struct {
	grpc.ServerStream
}

func (x *storagePullServer) Send(m *Ciphertext) error {
	return x.ServerStream.SendMsg(m)
}

func _Storage_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Address)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Storage/Stat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).Stat(ctx, req.(*Address))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Address)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Storage/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).Delete(ctx, req.(*Address))
	}
	return interceptor(ctx, in, info, handler)
}

var _Storage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Storage",
	HandlerType: (*StorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stat",
			Handler:    _Storage_Stat_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Storage_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Push",
			Handler:       _Storage_Push_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Pull",
			Handler:       _Storage_Pull_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}

// DocumentClient is the client API for Document service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DocumentClient interface {
	// GET a document from Hoard
	Download(ctx context.Context, in *grant.Grant, opts ...grpc.CallOption) (Document_DownloadClient, error)
	// POST a document into Hoard
	Upload(ctx context.Context, opts ...grpc.CallOption) (Document_UploadClient, error)
}

type documentClient struct {
	cc *grpc.ClientConn
}

func NewDocumentClient(cc *grpc.ClientConn) DocumentClient {
	return &documentClient{cc}
}

func (c *documentClient) Download(ctx context.Context, in *grant.Grant, opts ...grpc.CallOption) (Document_DownloadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Document_serviceDesc.Streams[0], "/api.Document/Download", opts...)
	if err != nil {
		return nil, err
	}
	x := &documentDownloadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Document_DownloadClient interface {
	Recv() (*PlaintextAndMeta, error)
	grpc.ClientStream
}

type documentDownloadClient struct {
	grpc.ClientStream
}

func (x *documentDownloadClient) Recv() (*PlaintextAndMeta, error) {
	m := new(PlaintextAndMeta)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *documentClient) Upload(ctx context.Context, opts ...grpc.CallOption) (Document_UploadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Document_serviceDesc.Streams[1], "/api.Document/Upload", opts...)
	if err != nil {
		return nil, err
	}
	x := &documentUploadClient{stream}
	return x, nil
}

type Document_UploadClient interface {
	Send(*PlaintextAndGrantSpecAndMeta) error
	CloseAndRecv() (*grant.Grant, error)
	grpc.ClientStream
}

type documentUploadClient struct {
	grpc.ClientStream
}

func (x *documentUploadClient) Send(m *PlaintextAndGrantSpecAndMeta) error {
	return x.ClientStream.SendMsg(m)
}

func (x *documentUploadClient) CloseAndRecv() (*grant.Grant, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(grant.Grant)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DocumentServer is the server API for Document service.
type DocumentServer interface {
	// GET a document from Hoard
	Download(*grant.Grant, Document_DownloadServer) error
	// POST a document into Hoard
	Upload(Document_UploadServer) error
}

// UnimplementedDocumentServer can be embedded to have forward compatible implementations.
type UnimplementedDocumentServer struct {
}

func (*UnimplementedDocumentServer) Download(req *grant.Grant, srv Document_DownloadServer) error {
	return status.Errorf(codes.Unimplemented, "method Download not implemented")
}
func (*UnimplementedDocumentServer) Upload(srv Document_UploadServer) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}

func RegisterDocumentServer(s *grpc.Server, srv DocumentServer) {
	s.RegisterService(&_Document_serviceDesc, srv)
}

func _Document_Download_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(grant.Grant)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DocumentServer).Download(m, &documentDownloadServer{stream})
}

type Document_DownloadServer interface {
	Send(*PlaintextAndMeta) error
	grpc.ServerStream
}

type documentDownloadServer struct {
	grpc.ServerStream
}

func (x *documentDownloadServer) Send(m *PlaintextAndMeta) error {
	return x.ServerStream.SendMsg(m)
}

func _Document_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DocumentServer).Upload(&documentUploadServer{stream})
}

type Document_UploadServer interface {
	SendAndClose(*grant.Grant) error
	Recv() (*PlaintextAndGrantSpecAndMeta, error)
	grpc.ServerStream
}

type documentUploadServer struct {
	grpc.ServerStream
}

func (x *documentUploadServer) SendAndClose(m *grant.Grant) error {
	return x.ServerStream.SendMsg(m)
}

func (x *documentUploadServer) Recv() (*PlaintextAndGrantSpecAndMeta, error) {
	m := new(PlaintextAndGrantSpecAndMeta)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Document_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Document",
	HandlerType: (*DocumentServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Download",
			Handler:       _Document_Download_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Upload",
			Handler:       _Document_Upload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api.proto",
}
