name: test
on:
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - uses: actions/checkout@v1
    - run: make build
    - run: make test
    - run: make test_js

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: make docker_build

  charts:
    runs-on: ubuntu-latest
    env:
      CM_USERNAME: ${{ secrets.CM_USERNAME }}
      CM_PASSWORD: ${{ secrets.CM_PASSWORD }}
      CM_URL:  ${{ secrets.CM_URL }}
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --unshallow --prune
      - run: make helm_package
